# Default values for webapp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

webapp:
  image: cnaveenss/webapp_test
  tag: 3.3
  replicas: 3

postgres:
  image: postgres
  tag: 15
  replicas: 1
  password: P0stgres
  host: postgres-headless
